/datum/unit_test/mob_onslaught
	name = "GAMEMODE: Mob Onslaught hidden wave integration"
	groups = list("generic", "simple mob ai")

/datum/unit_test/mob_onslaught/start_test()
	var/turf/spawn_turf = locate(10, 10, 1)
	var/turf/target_turf = get_step(spawn_turf, NORTH)
	if(!spawn_turf || !target_turf)
		return TEST_FAIL("Could not locate adjacent turfs for the Mob Onslaught test.")
	for(var/turf/test_turf in RANGE_TURFS(5, target_turf))
		test_turf.ChangeTurf(/turf/simulated/floor)

	var/datum/game_mode/mob_onslaught/mode = new
	if(mode.mode_duration != 30 MINUTES)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught is not configured for a 30-minute round.")
	if(mode.grace_period != 5 MINUTES)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught is not configured with a five-minute grace period.")
	if(mode.canon_type != /singleton/canonicity/non_canon_event)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught is not configured as a non-canon event.")
	if(!(TRAIT_DEAFNESS_IMMUNITY in mode.player_traits))
		qdel(mode)
		return TEST_FAIL("Mob Onslaught does not grant the generic deafness-immunity player trait.")
	if(mode.spawn_protection_grace_period != 2 MINUTES)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught latejoin protection does not use a two-minute post-departure grace period.")
	if(mode.get_desired_wave_size(1, 1) != 1 || mode.get_desired_wave_size(1, 5) != 16 || mode.get_desired_wave_size(3, 4) != 24)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught wave size does not scale exponentially from the active player count.")
	if(mode.get_active_mob_cap(1) != 20 || mode.get_active_mob_cap(5) != 100)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught does not allow twenty active hostile mobs per eligible player.")
	if(mode.ship_infestation_size != 30)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught does not configure the expected thirty-mob uncapped ship infestation.")
	if(length(mode.get_next_wave_radio_lines()) < 5)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught does not provide a varied pool of Intern next-wave radio messages.")
	if(mode.allow_overmap_hazards || mode.allow_away_sites || mode.announce_roundstart_sensor_report)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught does not disable its optional overmap content and roundstart sensor announcement.")
	var/mob/living/carbon/human/latejoiner = new(target_turf)
	mode.handle_latejoin(latejoiner)
	if(!(latejoiner.status_flags & GODMODE) || length(mode.spawn_protections) != 1)
		qdel(latejoiner)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught latejoiner did not receive mode-owned invulnerability.")
	var/datum/mob_onslaught_spawn_protection/protection = mode.spawn_protections[1]
	var/area/original_latejoin_area = get_area(target_turf)
	var/area/departure_area = new
	target_turf.change_area(original_latejoin_area, departure_area)
	mode.process_spawn_protections()
	if(!protection.expires_at || protection.expires_at != world.time + mode.spawn_protection_grace_period)
		target_turf.change_area(departure_area, original_latejoin_area)
		qdel(departure_area)
		qdel(latejoiner)
		qdel(mode)
		return TEST_FAIL("Leaving the latejoin area did not start the spawn-protection grace period.")
	protection.expires_at = world.time
	mode.process_spawn_protections()
	if((latejoiner.status_flags & GODMODE) || length(mode.spawn_protections))
		target_turf.change_area(departure_area, original_latejoin_area)
		qdel(departure_area)
		qdel(latejoiner)
		qdel(mode)
		return TEST_FAIL("Expired Mob Onslaught spawn protection did not revoke invulnerability.")
	target_turf.change_area(departure_area, original_latejoin_area)
	qdel(departure_area)
	qdel(latejoiner)
	var/obj/structure/closet/secure_closet/test_locker = new(spawn_turf)
	if(length(mode.get_locker_melee_pool()) < 15 || length(mode.get_locker_projectile_loadouts()) < 6 || length(mode.get_locker_energy_pool()) < 9)
		qdel(test_locker)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught weapon pools do not provide the expected expanded variety.")
	if(!mode.supply_locker(test_locker))
		qdel(test_locker)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught failed to supply a departmental locker.")
	var/melee_count = 0
	var/projectile_count = 0
	var/energy_count = 0
	var/magazine_count = 0
	var/obj/item/gun/projectile/projectile_weapon
	for(var/obj/item/locker_item in test_locker)
		if(is_type_in_list(locker_item, mode.get_locker_melee_pool()))
			melee_count++
		if(istype(locker_item, /obj/item/gun/projectile))
			projectile_count++
			projectile_weapon = locker_item
		if(istype(locker_item, /obj/item/gun/energy))
			energy_count++
		if(istype(locker_item, /obj/item/ammo_magazine))
			magazine_count++
	if(melee_count != 1 || projectile_count != 1 || energy_count != 1 || magazine_count != 2)
		qdel(test_locker)
		qdel(mode)
		return TEST_FAIL("A supplied locker did not receive one melee weapon, one projectile weapon, two spare magazines, and one energy weapon.")
	for(var/obj/item/ammo_magazine/spare_magazine in test_locker)
		if(!is_type_in_list(spare_magazine, projectile_weapon.allowed_magazines))
			qdel(test_locker)
			qdel(mode)
			return TEST_FAIL("A supplied locker received a spare magazine incompatible with its projectile weapon.")
	qdel(test_locker)
	var/mob/living/simple_animal/unit_test_ai_target/target_mob = new(target_turf)
	var/mob/living/simple_animal/hostile/spawned_mob = mode.spawn_wave_mob(/mob/living/simple_animal/hostile/scarybat, spawn_turf, target_mob)
	if(!spawned_mob || spawned_mob.faction != "mob_onslaught" || spawned_mob.ai_holder?.target != target_mob)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A wave mob did not receive the shared faction and holder-owned player target.")
	if(!(spawned_mob in mode.active_wave_mobs) || mode.total_spawned != 1)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("The mode did not track its spawned hostile.")
	if(!spawned_mob.ai_holder?.instant_door_destruction || !spawned_mob.ai_holder.use_astar)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught hostile was not configured to path through and destroy blocking doors.")
	var/list/test_path = spawned_mob.ai_holder.get_path(target_turf, 0, 10)
	if(length(test_path) && test_path[1] == spawn_turf)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("The AI holder retained its current turf as the first A* movement step.")
	var/obj/structure/machinery/door/window/test_windoor = new(spawn_turf)
	test_windoor.set_dir(get_dir(spawn_turf, target_turf))
	if(!spawned_mob.ai_holder.destroy_blocking_door(get_dir(spawn_turf, target_turf)) || !QDELETED(test_windoor))
		qdel(test_windoor)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught hostile failed to destroy a blocking windoor.")
	var/obj/structure/machinery/door/airlock/test_airlock = new(target_turf)
	var/list/door_path = spawned_mob.ai_holder.get_path(target_turf, 0, 10)
	if(!length(door_path) || door_path[1] != target_turf)
		qdel(test_airlock)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught hostile could not plan a path through a destructible airlock.")
	test_airlock.CollidedWith(spawned_mob)
	if(!QDELETED(test_airlock))
		qdel(test_airlock)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught hostile failed to destroy an airlock it collided with.")
	var/obj/structure/railing/test_railing = new(spawn_turf)
	test_railing.set_dir(get_dir(spawn_turf, target_turf))
	var/list/railing_path = spawned_mob.ai_holder.get_path(target_turf, 0, 10)
	if(!length(railing_path) || railing_path[1] != target_turf)
		qdel(test_railing)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught hostile standing on a railing could not plan a path through it.")
	if(!spawned_mob.ai_holder.destroy_blocking_door(get_dir(spawn_turf, target_turf)) || !QDELETED(test_railing))
		qdel(test_railing)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught hostile failed to destroy a blocking railing.")
	if(spawned_mob.ai_holder?.mode_ai_owner != mode)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A wave mob was not connected to Mob Onslaught's idle convergence rules.")
	var/mob/living/simple_animal/hostile/ambient_mob = mode.spawn_wave_mob(/mob/living/simple_animal/hostile/scarybat, spawn_turf, target_mob, FALSE, FALSE, FALSE)
	if(!ambient_mob || ambient_mob.ai_holder?.target || ambient_mob.ai_holder?.mode_ai_owner || ambient_mob.ai_holder?.use_astar || !(ambient_mob in mode.uncapped_ship_mobs))
		qdel(ambient_mob)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("An uncapped ship infestation mob received wave targeting or Central Ring convergence orders.")
	qdel(ambient_mob)
	mode.uncapped_ship_mobs -= ambient_mob
	var/list/ambush_turfs = RANGE_TURFS(5, target_turf)
	var/area/original_ambush_area = get_area(target_turf)
	var/area/horizon/ambush_area = new
	for(var/turf/ambush_turf as anything in ambush_turfs)
		ambush_turf.change_area(original_ambush_area, ambush_area)
	var/ambush_spawned = mode.spawn_player_ambushes(list(target_mob), list(/mob/living/simple_animal/hostile/scarybat), 2)
	if(ambush_spawned != 2 || length(mode.uncapped_ship_mobs) != 2)
		for(var/turf/ambush_turf as anything in ambush_turfs)
			ambush_turf.change_area(ambush_area, original_ambush_area)
		qdel(ambush_area)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A player outside the Central Ring did not receive one uncapped ambush mob per wave number.")
	for(var/mob/living/simple_animal/hostile/ambush_mob as anything in mode.uncapped_ship_mobs)
		if(ambush_mob.ai_holder?.target != target_mob || (ambush_mob in mode.active_wave_mobs))
			for(var/turf/ambush_turf as anything in ambush_turfs)
				ambush_turf.change_area(ambush_area, original_ambush_area)
			qdel(ambush_area)
			qdel(spawned_mob)
			qdel(target_mob)
			qdel(mode)
			return TEST_FAIL("A player ambush mob counted toward the wave cap or lacked its assigned player target.")
		qdel(ambush_mob)
	mode.uncapped_ship_mobs.Cut()
	for(var/turf/ambush_turf as anything in ambush_turfs)
		ambush_turf.change_area(ambush_area, original_ambush_area)
	qdel(ambush_area)
	var/area/original_target_area = get_area(target_turf)
	var/area/horizon/hallway/primary/deck_1/central/safe_area = new
	target_turf.change_area(original_target_area, safe_area)
	if(!mode.is_safe_zone(target_turf))
		target_turf.change_area(safe_area, original_target_area)
		qdel(safe_area)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught could not identify the Central Ring safe zone.")
	if(mode.is_valid_spawn_turf(target_turf, list()))
		target_turf.change_area(safe_area, original_target_area)
		qdel(safe_area)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("The Central Ring was accepted as a Mob Onslaught spawn turf.")
	if(mode.spawn_player_ambushes(list(target_mob), list(/mob/living/simple_animal/hostile/scarybat), 2))
		target_turf.change_area(safe_area, original_target_area)
		qdel(safe_area)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A player inside the Central Ring received an uncapped wave ambush.")
	if(!spawned_mob.ai_holder.can_attack(target_mob, FALSE))
		target_turf.change_area(safe_area, original_target_area)
		qdel(safe_area)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("The Central Ring incorrectly prevented an onslaught mob from attacking a target.")
	target_turf.change_area(safe_area, original_target_area)
	qdel(safe_area)
	var/target_health_before_carp = target_mob.health
	var/mob/living/simple_animal/hostile/carp/wave_carp = mode.spawn_wave_mob(/mob/living/simple_animal/hostile/carp, spawn_turf, target_mob)
	wave_carp.ai_holder.think()
	if(target_mob.health >= target_health_before_carp)
		qdel(wave_carp)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("A Mob Onslaught space carp did not attack its assigned adjacent player target.")
	qdel(wave_carp)

	var/list/early_pool = mode.get_regular_mob_pool(1)
	var/list/escalated_pool = mode.get_regular_mob_pool(6)
	if(length(early_pool) < 9 || length(escalated_pool) < 28)
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught does not provide the expected expanded non-humanoid mob variety.")
	if((/mob/living/simple_animal/hostile/faithless in escalated_pool) || (/mob/living/simple_animal/hostile/bear in early_pool) || !(/mob/living/simple_animal/hostile/bear in escalated_pool))
		qdel(spawned_mob)
		qdel(target_mob)
		qdel(mode)
		return TEST_FAIL("Mob Onslaught difficulty pools did not escalate at the configured wave.")
	var/list/explosive_mob_types = list(
		/mob/living/simple_animal/hostile/plasmageist,
		/mob/living/simple_animal/hostile/carp/bloater,
		/mob/living/simple_animal/hostile/hivebot/bomber,
		/mob/living/simple_animal/hostile/icarus_drone
	)
	var/list/late_boss_pool = mode.get_boss_mob_pool(10)
	for(var/explosive_mob_type in explosive_mob_types)
		if((explosive_mob_type in escalated_pool) || (explosive_mob_type in late_boss_pool))
			qdel(spawned_mob)
			qdel(target_mob)
			qdel(mode)
			return TEST_FAIL("Mob Onslaught includes an explosion-producing mob capable of deafening the crew.")

	var/list/hidden_turfs = mode.get_hidden_spawn_turfs(list(target_mob))
	for(var/turf/hidden_turf as anything in hidden_turfs)
		if(isspaceturf(hidden_turf) || !istype(hidden_turf, /turf/simulated/floor))
			qdel(spawned_mob)
			qdel(target_mob)
			qdel(mode)
			return TEST_FAIL("The hidden spawn selector returned a space or non-floor turf.")
		if(hidden_turf in view(world.view, target_mob))
			qdel(spawned_mob)
			qdel(target_mob)
			qdel(mode)
			return TEST_FAIL("The hidden spawn selector returned a turf visible to its player anchor.")

	qdel(spawned_mob)
	qdel(target_mob)
	qdel(mode)
	return TEST_PASS("Mob Onslaught disables optional overmap content, supplies lockers, protects latejoiners, keeps carp hostile, excludes Central Ring spawning without suppressing attacks, and spawns hostiles only on hidden non-space floor turfs.")
